version: '3.4'

x-common: &common
  image: app:local
  labels:
    com.app: app
  networks:
    - app
  volumes:
    - build:/app/build/

services:
  builder:
    volumes:
      - build:/app/build/
      - .:/app:delegated
    <<: *common
    build: .
    container_name: app-builder
    working_dir: /app
    command: ['node', 'dist/main']

networks:
  app:

volumes:
  build: