version: '3.4'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${NESTJS_PORT}:${NESTJS_PORT}
    env_file:
      - .env
    networks:
      - main
    depends_on:
      - dgraph
      - zero
      - nats
  zero:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    volumes:
      - dgraph:/dgraph
    restart: on-failure
    command: dgraph zero --my=zero:5080
    networks:
      - main
  dgraph:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    volumes:
      - dgraph:/dgraph
    restart: on-failure
    command: dgraph alpha --my=dgraph:7080 --lru_mb=2048 --zero=zero:5080
    networks:
      - main
  nats:
    image: nats:${NATS_VERSION}
    command: "-c /etc/nats/nats.conf"
    volumes:
       - ./config/:/etc/nats
    ports:
      - '4222:4222'
      - '8222:8222'
      - '9222:9222'

networks:
  main:

volumes:
  dgraph: